add layout
js-tasks-ru/htmlcss-20240216_kseniya4 pull request #3
Opened 2024-02-26 13:59 UTC by kseniyamikhel

2024-02-26 13:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-28 09:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 14:09 UTC, GSemikozov requested changes

2024-03-04 14:09 UTC, GSemikozov commented on assets/fonts/inter-font.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
можно в том же файле где и другой шрифт

2024-03-04 14:09 UTC, GSemikozov commented on components/card/card.css
> +    flex-grow: 1;
мы не знаем заранее о контексте, а именно - что родитель будет флексом, так что лучше убрать

2024-03-05 12:33 UTC, kseniyamikhel commented on assets/fonts/inter-font.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
Я изначально так и хотела, но при редактировании файла assets/fonts/fonts.css мне шторм выдает предупреждение - Generated source file should not be edited. The changes will be lost when source are regenerated. Поэтому я и сделала отдельный файл

2024-03-05 12:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-05 12:36 UTC, kseniyamikhel commented on components/card/card.css
> +    flex-grow: 1;
поправила

2024-03-05 21:29 UTC, GSemikozov requested changes

2024-03-05 21:29 UTC, GSemikozov commented on assets/fonts/inter-font.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
это предупреждение не о том) 
просто надо сохранить файл перед закрытием. 
этот момент все еще актуален.

2024-03-06 07:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-06 07:21 UTC, kseniyamikhel commented on assets/fonts/inter-font.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
исправила

2024-03-06 09:22 UTC, GSemikozov approved these changes

2024-03-06 09:22 UTC, merged