added solution for task Lection 2 Histogram
js-tasks-ru/htmlcss-20240216_kseniya4 pull request #6
Opened 2024-03-06 10:10 UTC by kseniyamikhel

2024-03-06 10:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-06 15:30 UTC, GSemikozov requested changes

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +* {
ни в коем случае не используем универсальный селектор, тем более в файле стилей компонента

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-family: 'Inter', sans-serif;
это наследуемое свойство, так что можно задать один раз на уровне класса блока

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-container {
лишнее

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    --primary: #4263EB;
такая переменная есть в root

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
лишнее

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    line-height: 24px;
margin-top: 3px

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 70px;
50

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 70px;
+ gap: 1px

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 1px;
лишнее

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 5px 0;
`6px 0 39px`

2024-03-06 15:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 5px 0;
и сам элемент - div, должен быть под histogram__info

2024-03-08 07:35 UTC, GSemikozov approved these changes

2024-03-08 07:35 UTC, merged