added solution for task Lection 2 Skeleton
js-tasks-ru/htmlcss-20240216_kseniya4 pull request #7
Opened 2024-03-06 10:21 UTC by kseniyamikhel

2024-03-06 10:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-06 15:33 UTC, GSemikozov requested changes

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton-container {
лишнее, удалим

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 100%;
лишнее

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px;
`24 40 32 24`

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    justify-content: space-evenly;
gap: 8px

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 50%;
а почему 50?

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 0 15px;
точно нужны паддинги?

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title .skeleton__row:first-child {
просто элемент и модификаторы (.skeleton__row_small, .skeleton__row_medium и тд)

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px 18px 0 0;
не нужно, и сам элемент кажется лишним

2024-03-06 15:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__description .skeleton__row {
если сделать общую колонку для линий .skeleton__lines с gap: 8px, то это не надо

2024-03-07 11:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-07 13:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-07 14:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-07 20:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-07 20:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-08 07:36 UTC, GSemikozov requested changes

2024-03-08 07:36 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +            <div class="skeleton__image"></div>
картинку и тайтл надо завернуть в общий элемент и задать gap

2024-03-08 07:36 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 0 16px 24px 0;
и тогда вот это будет лишним

2024-03-08 11:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-11 15:48 UTC, GSemikozov approved these changes

2024-03-11 15:48 UTC, merged