added solution for Lection 3 Modal
js-tasks-ru/htmlcss-20240216_kseniya4 pull request #9
Opened 2024-03-11 14:44 UTC by kseniyamikhel

2024-03-11 14:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 09:00 UTC, GSemikozov requested changes

2024-03-12 09:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
не нужны, все компоненты собираются в main.css

2024-03-12 09:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__background {
это лишний элемент, все стили перемещаем в .modal (только фон лучше через rgba)

2024-03-12 09:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
а во здесь как раз уже absolute | relative

2024-03-12 11:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 21:03 UTC, GSemikozov approved these changes

2024-03-12 21:03 UTC, merged